image:
  file: .gitpod.DockerFile
tasks:
  - name: ybu
    init:
      pip install --upgrade pip
      pip install html2text
      pip install jq
      pip install ipython-sql~=0.5 --upgrade
      pip install sqlparse
      pip install SQLAlchemy --upgrade 
      pip install psycopg2-binary
      pip install pgspecial
    command: |
      yugabyted start  \
        --advertise_address="127.0.0.1"  \
        --base_dir=/home/gitpod/var/node1  \
        --cloud_location=cloud1.region1.zone1  \
        --fault_tolerance=zone  \
        --master_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --master_webserver_port=7000  \
        --tserver_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --tserver_webserver_port=8200
      yugabyted start  \
        --advertise_address="127.0.0.2"  \
        --base_dir=/home/gitpod/var/node2  \
        --cloud_location=cloud1.region1.zone2  \
        --fault_tolerance=zone  \
        --join="127.0.0.1"  \
        --master_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --master_webserver_port=7000  \
        --tserver_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --tserver_webserver_port=8200
      yugabyted start  \
        --advertise_address="127.0.0.3"  \
        --base_dir=/home/gitpod/var/node3  \
        --cloud_location=cloud1.region1.zone3  \
        --fault_tolerance=zone  \
        --join="127.0.0.1"  \
        --master_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --master_webserver_port=7000  \
        --tserver_flags="yb_num_shards_per_tserver=1,ysql_num_shards_per_tserver=1,ysql_beta_features=true,ysql_enable_packed_row=false"  \
        --tserver_webserver_port=8200
      yugabyted configure data_placement --fault_tolerance=zone
      yugabyted status
      gp open 01_Lab_Setup.ipynb

ports:
  - port: 5433
    description: YSQL API Port
    onOpen: ignore
  - port: 7000
    description: YB-Master UI Port
    onOpen: notify
  - port: 7100
    description: YB-Master API Port
    onOpen: ignore
  - port: 8200
    description: YB-TServer UI Port
    onOpen: notify
  - port: 9000-9040
    description: Jupyter Notebook ports
    onOpen: ignore
  - port: 9042
    description: YCQL API Port
    onOpen: ignore
  - port: 9100
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 12000
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 15433
    onOpen: open-browser
  - port: 37843
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
