image:
  file: .gitpod.DockerFile
tasks:
  - name: htop
    before: |
      sdk install java < /dev/null
    init: |
      pip install --upgrade pip
      pip install html2text
      pip install jq
      pip install --upgrade jupysql
      pip install sqlparse
      pip install SQLAlchemy --upgrade 
      pip install psycopg2-binary
      pip install pickleshare
      pip install pgspecial
    command: |
      htop
  - name: ybu-lab
    init: |
      (
        set -e
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node1/yugabyted.conf
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node2/yugabyted.conf
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node3/yugabyted.conf
        echo "$(date) –  copied yugabyted.conf"
        chmod 777 ${GITPOD_REPO_ROOT}/start_all.sh
        chmod 777 ${GITPOD_REPO_ROOT}/stop_and_destroy_all.sh
      )
    command: |
      cd ${GITPOD_REPO_ROOT}
      ./start_all.sh
      gp open 01_Lab_Setup.ipynb
ports:
  - port: 5433
    description: YSQL API Port
    onOpen: ignore
  - port: 7000
    description: YB-Master UI Port
    onOpen: notify
  - port: 7100
    description: YB-Master API Port
    onOpen: ignore
  - port: 8200
    description: YB-TServer UI Port
    onOpen: notify
  - port: 9000-9040
    description: Jupyter Notebook ports
    onOpen: ignore
  - port: 9042
    description: YCQL API Port
    onOpen: ignore
  - port: 9100
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 12000
    description:  YB-TServer API Port
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 15433
    onOpen: open-browser
  - port: 37843
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
